import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
// import SmothScroll from "@/components/SmothScroll/SmothScroll";

// export const metadata = {
//   title: "It Institute",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    // <SmothScroll>
      <div className=" overflow-x-hidden relative scrollbar-thumb-orange-500 scrollbar-thin">
        <Navbar />
        {children}
        <Footer />
      </div>
    // </SmothScroll>
  );
}
