"use client";

import Sidebar from "@/components/DashboardComponents/Sidebar";
import PrivateRoute from "@/private/PrivateRoute";
import { useState } from "react";
import { GiHamburgerMenu } from "react-icons/gi";
// export const metadata = {
//   title: "It Institute",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [toggle, setToggle] = useState(false);
  return (
    <PrivateRoute>
      <div className="flex gap-5 relative overflow-x-hidden">
        <div
          className={`${
            toggle
              ? "translate-x-0 top-14 duration-500"
              : "-translate-x-full top-14 duration-500"
          } w-[250px] md:flex md:translate-x-0 fixed md:top-0 left-0 bg-white z-30`}
        >
          <Sidebar setToggle={setToggle} toggle={toggle}></Sidebar>
        </div>
        <div className="w-full">
          <div className="h-14 py-2 bg-slate-200 w-full md:ml-[250px] flex gap-5 items-center px-5">
            <div
              onClick={() => setToggle(!toggle)}
              className="text-2xl md:hidden flex cursor-pointer"
            >
              <GiHamburgerMenu />
            </div>
            <p>this section for all important link</p>
          </div>
          <div className="p-5 md:ml-[250px] w-full">{children}</div>
        </div>
      </div>
    </PrivateRoute>
  );
}
